export * from './Footer'
export * from './Header'
export * from './sections/Hero'
export * from './sections/Tecnologies'
export * from './sections/Devices'
export * from './sections/Questions'
export * from './sections/CTA'
export * from './sections/Team'